version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
  rtdb-sync-pub:
    build: .
    depends_on:
      - redis
      - mqtt-broker
