
__all__ = ["CLIENT_CONNECTED", "MQTT_BROKER_DOWN", "MQTT_BROKER_NOT_FOUND"]

CLIENT_CONNECTED = "CLIENT_CONNECTED"
MQTT_BROKER_DOWN = "MQTT_BROKER_DOWN"
MQTT_BROKER_NOT_FOUND = "MQTT_BROKER_NOT_FOUND"
